---
title: "fitting RelDists distributions with gamlss"
author: "Jaime Mosquera & Johan Marin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fitDistPlus}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "##"
)
```

**This is a temporal vignette, only for some tests**

Random data generation with `EW` family:

```{r}
require(RelDists)
y <- rEW(n=100, mu=2, sigma=1.5, nu=0.5)
```


Fitting with traditional gamlss families:

```{r, message=FALSE, warning=FALSE}
require(gamlss)
fits <- fitDist(y, type="realplus")
fits$fits
fits$failed
```

Fitting with gamlss  some our  families:

```{r, message=FALSE, warning=FALSE}
require(gamlss)
require(RelDists)

familias <- c("EW", "ExW", "FWE")

md <- gamlss(y~1, control=gamlss.control(n.cyc=500, trace=FALSE), family=NULL)
fits <- chooseDist(md, type = "extra",  extra = familias)
fits
```

Fitting with gamlss families and our `"reldists"` family:

```{r eval=FALSE}
require(gamlss)
require(RelDists)
fits <- fitDistPlus(y, type="reldists")

fits$fits
fits$failed
```
