summary.initValOW <- function(object, ...){
  cat("--------------------------------------------------------------------\n")
  cat("Initial Values\n")
  cat(paste0("sigma = ", object$sigma.start, "\n"))
  cat(paste0("nu = ", object$nu.start, "\n\n"))
  cat("--------------------------------------------------------------------\n")
  cat("Search Regions\n")
  cat("For sigma: ")
  cat(paste0(object$sigma.valid, "\n"))
  cat("For nu: ")
  cat(paste0(object$nu.valid, "\n\n"))
  cat("--------------------------------------------------------------------\n")
  cat("Hazard shape: ")
  cat(object$hazard_type)
}
